import { writable } from 'svelte/store';

export type ResultRow = {
	inputID: string,
	inputRank?: string,
	inputName: string,
	matchType: string,
	ID: string,
	rank: string,
	label?: string,
	scientificName: string,
	authorship: string,
	status: string,
	acceptedName?: string,
	classification?: string,
	issues?: string,
}

let acceptedRows: ResultRow[] = [

]

export let acceptedStore = writable<ResultRow[]>(acceptedRows)

let emptyTestRows: ResultRow[] = [

]

let resultRows: ResultRow[] = 
[
  {
    "inputID": "tp",
    "inputRank": "",
    "inputName": "",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": "UNPARSABLE_NAME"
  },
  {
    "inputID": 1,
    "inputRank": "",
    "inputName": "Dupoa labradorica",
    "matchType": "variant",
    "ID": "f_Yu7cBp0esx2hUuQmLAr1",
    "rank": "species",
    "label": "× Dupoa labradorica (Steud.) J.Cay. & Darbysh.",
    "scientificName": "× Dupoa labradorica",
    "authorship": "(Steud.) J.Cay. & Darbysh.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:× Dupoa J.Cay. & Darbysh.|FAMILY:Poaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 2,
    "inputRank": "",
    "inputName": "Hedyosmum mexicanum",
    "matchType": "variant",
    "ID": "pEpl3JT6UK7P5tKH1KQp-0",
    "rank": "species",
    "label": "Hedyosmum mexicanum Cordem. ex Baill.",
    "scientificName": "Hedyosmum mexicanum",
    "authorship": "Cordem. ex Baill.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Hedyosmum Sw.|FAMILY:Chloranthaceae R. Br. ex Sims|ORDER:Chloranthales Mart.|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 3,
    "inputRank": "",
    "inputName": "Metrosideros polymorpha Gaudich.",
    "matchType": "exact",
    "ID": "F53jY6wV-sN79_VlpPtqY1",
    "rank": "species",
    "label": "Metrosideros polymorpha Gaudich.",
    "scientificName": "Metrosideros polymorpha",
    "authorship": "Gaudich.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Metrosideros Banks ex Gaertn.|SUBFAMILY:Myrtoideae Sweet|FAMILY:Myrtaceae Juss.|ORDER:Myrtales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 4,
    "inputRank": "",
    "inputName": "Terminalia sericea",
    "matchType": "variant",
    "ID": "RDkO9iPvGs8ABKcoPPA_R1",
    "rank": "species",
    "label": "Terminalia sericea Burch. ex DC.",
    "scientificName": "Terminalia sericea",
    "authorship": "Burch. ex DC.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Terminalia L.|SUBFAMILY:Combretoideae Beilschm.|FAMILY:Combretaceae R. Br.|ORDER:Myrtales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 5,
    "inputRank": "",
    "inputName": "??Artocarpus obtusus",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 6,
    "inputRank": "",
    "inputName": "??Dryobalanops aromatica",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 7,
    "inputRank": "",
    "inputName": "??Ficus sp.",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 8,
    "inputRank": "",
    "inputName": "??Horsfieldia palidicaura",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 9,
    "inputRank": "",
    "inputName": "??Madhuca carassipes",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 10,
    "inputRank": "",
    "inputName": "??Parishia sericea",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 11,
    "inputRank": "",
    "inputName": "??Shorea fallax",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": "",
    "inputRank": "",
    "inputName": "",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": "NOT_INTERPRETED;UNPARSABLE_NAME"
  },
  {
    "inputID": 13,
    "inputRank": "",
    "inputName": "#Acacia?iteaphylla?F.Muell. ex Benth.",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 14,
    "inputRank": "",
    "inputName": "#Acacia?saligna?(Labill.) H.L.Wendl.",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 15,
    "inputRank": "",
    "inputName": "(Asteraceae2 sp.",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 16,
    "inputRank": "",
    "inputName": "(fabaceae)",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 17,
    "inputRank": "",
    "inputName": "(hippocrateaceae) atenumembra",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 18,
    "inputRank": "",
    "inputName": "(lauraceae) chiquita",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 19,
    "inputRank": "",
    "inputName": "(lauraceae) impresofalso",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 20,
    "inputRank": "",
    "inputName": "(lauraceae) pubescente",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 21,
    "inputRank": "",
    "inputName": "(malpighiaceae) bulondu",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 22,
    "inputRank": "",
    "inputName": "(myrtaceae) cortezapeq",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 23,
    "inputRank": "",
    "inputName": "(myrtaceae) smedcheilo",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 24,
    "inputRank": "",
    "inputName": "(picramniaceae) sp.nov.",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 25,
    "inputRank": "",
    "inputName": "(u_angio11492 sp",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 26,
    "inputRank": "",
    "inputName": "(u_angio5 sp",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 27,
    "inputRank": "",
    "inputName": "(u_Araceae sp11579",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 28,
    "inputRank": "",
    "inputName": "(u_Aster14327 sp",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 29,
    "inputRank": "",
    "inputName": "(u_Crasulaceae sp14326",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 30,
    "inputRank": "",
    "inputName": "(u_Herb2874 sp",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 31,
    "inputRank": "",
    "inputName": "(u_liana sp6402",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 32,
    "inputRank": "",
    "inputName": "(u_Malphig sp6395",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 33,
    "inputRank": "",
    "inputName": "(u_nanophyte sp6378",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 34,
    "inputRank": "",
    "inputName": "(u_Orchid3599 sp",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 35,
    "inputRank": "",
    "inputName": "(u_Poaceae sp1",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 36,
    "inputRank": "",
    "inputName": "(u_Poaceae sp2049",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 37,
    "inputRank": "",
    "inputName": "(u_Polypodiaceae sp6388",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 38,
    "inputRank": "",
    "inputName": "(u_Solana11399 sp",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 39,
    "inputRank": "",
    "inputName": "(u_Vitaceae sp14439",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 40,
    "inputRank": "",
    "inputName": "?Betulaceae sp.",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": "INDETERMINED"
  },
  {
    "inputID": 41,
    "inputRank": "",
    "inputName": "?Pachygone ovata",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": "PARTIALLY_PARSABLE_NAME"
  },
  {
    "inputID": 42,
    "inputRank": "",
    "inputName": "10 Tree species",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 43,
    "inputRank": "",
    "inputName": 1398,
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 44,
    "inputRank": "",
    "inputName": "5 Tall Catinga species",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 45,
    "inputRank": "",
    "inputName": "8 Mixed forest species",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 46,
    "inputRank": "",
    "inputName": "9 Tree species",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 47,
    "inputRank": "",
    "inputName": "Aa argyrolepis",
    "matchType": "variant",
    "ID": "HzruoTd7anNk90aF3DPf7",
    "rank": "species",
    "label": "Aa argyrolepis Rchb.f.",
    "scientificName": "Aa argyrolepis",
    "authorship": "Rchb.f.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Aa Rchb.f.|FAMILY:Orchidaceae|ORDER:Asparagales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 48,
    "inputRank": "",
    "inputName": "Aa denticulata",
    "matchType": "variant",
    "ID": "bzgvV2pJfO7r6WK4E4JAL0",
    "rank": "species",
    "label": "Aa denticulata Schltr.",
    "scientificName": "Aa denticulata",
    "authorship": "Schltr.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Aa Rchb.f.|FAMILY:Orchidaceae|ORDER:Asparagales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 49,
    "inputRank": "",
    "inputName": "Aa leucantha",
    "matchType": "variant",
    "ID": "GEzuA4SJNfuo78sxEfT631",
    "rank": "species",
    "label": "Aa leucantha (Rchb.f.) Schltr.",
    "scientificName": "Aa leucantha",
    "authorship": "(Rchb.f.) Schltr.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Aa Rchb.f.|FAMILY:Orchidaceae|ORDER:Asparagales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 50,
    "inputRank": "",
    "inputName": "Aa matthewsii",
    "matchType": "variant",
    "ID": "ehMUwBLNrANNDdhC1D7up2",
    "rank": "species",
    "label": "Aa matthewsii (Rchb.f.) Schltr.",
    "scientificName": "Aa matthewsii",
    "authorship": "(Rchb.f.) Schltr.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Aa Rchb.f.|FAMILY:Orchidaceae|ORDER:Asparagales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 51,
    "inputRank": "",
    "inputName": "Aa rosei",
    "matchType": "variant",
    "ID": "F5RifrVAXB9V5lOLd4bjd2",
    "rank": "species",
    "label": "Aa rosei Ames",
    "scientificName": "Aa rosei",
    "authorship": "Ames",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Aa Rchb.f.|FAMILY:Orchidaceae|ORDER:Asparagales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 52,
    "inputRank": "",
    "inputName": "Aa trilobulata",
    "matchType": "variant",
    "ID": "22ixDY1ArS9U0WmqzLBCA0",
    "rank": "species",
    "label": "Aa trilobulata Schltr.",
    "scientificName": "Aa trilobulata",
    "authorship": "Schltr.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Aa Rchb.f.|FAMILY:Orchidaceae|ORDER:Asparagales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 53,
    "inputRank": "",
    "inputName": "A-Agroelymus bowdenii",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 54,
    "inputRank": "",
    "inputName": "A-Argyrautia degeneri",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 55,
    "inputRank": "",
    "inputName": "Abama americana",
    "matchType": "variant",
    "ID": "B4INu1ljBsOhD_fMqns7-2",
    "rank": "species",
    "label": "Abama americana (Ker Gawl.) Morong",
    "scientificName": "Abama americana",
    "authorship": "(Ker Gawl.) Morong",
    "status": "synonym",
    "acceptedName": "Narthecium americanum Ker Gawl.",
    "classification": "SPECIES:Narthecium americanum Ker Gawl.|GENUS:Narthecium Huds.|FAMILY:Nartheciaceae|ORDER:Dioscoreales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 56,
    "inputRank": "",
    "inputName": "Abarema adenophora",
    "matchType": "variant",
    "ID": "-ScsbDkWmvfN7C1Jwe3Py",
    "rank": "species",
    "label": "Abarema adenophora (Ducke) Barneby & J.W.Grimes",
    "scientificName": "Abarema adenophora",
    "authorship": "(Ducke) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba adenophora (Ducke) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba adenophora (Ducke) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 57,
    "inputRank": "",
    "inputName": "Abarema auriculata",
    "matchType": "variant",
    "ID": "j_pJUPXRWEQB8pOsMMCFh1",
    "rank": "species",
    "label": "Abarema auriculata (Benth.) Barneby & J.W.Grimes",
    "scientificName": "Abarema auriculata",
    "authorship": "(Benth.) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba auriculata (Benth.) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba auriculata (Benth.) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 58,
    "inputRank": "",
    "inputName": "Abarema brachystachya",
    "matchType": "variant",
    "ID": "56wFod7HQVutBCgLusMJY",
    "rank": "species",
    "label": "Abarema brachystachya (DC.) Barneby & J.W.Grimes",
    "scientificName": "Abarema brachystachya",
    "authorship": "(DC.) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba brachystachya (DC.) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba brachystachya (DC.) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 59,
    "inputRank": "",
    "inputName": "Abarema cochleata",
    "matchType": "variant",
    "ID": "DEU19AMASCQHDWipCGjDf0",
    "rank": "species",
    "label": "Abarema cochleata (Willd.) Barneby & J.W.Grimes",
    "scientificName": "Abarema cochleata",
    "authorship": "(Willd.) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba cochleata (Willd.) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba cochleata (Willd.) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 60,
    "inputRank": "",
    "inputName": "Abarema curvicarpa",
    "matchType": "variant",
    "ID": "F_LVKha0vGtI5_2ZvXS4_0",
    "rank": "species",
    "label": "Abarema curvicarpa (H.S.Irwin) Barneby & J.W.Grimes",
    "scientificName": "Abarema curvicarpa",
    "authorship": "(H.S.Irwin) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba curvicarpa (H.S.Irwin) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba curvicarpa (H.S.Irwin) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 61,
    "inputRank": "",
    "inputName": "Abarema gallorum",
    "matchType": "variant",
    "ID": "HNlawyopeHQZ6_VdYz1FQ2",
    "rank": "species",
    "label": "Abarema gallorum Barneby & J.W.Grimes",
    "scientificName": "Abarema gallorum",
    "authorship": "Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba gallorum (Barneby & J.W.Grimes) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba gallorum (Barneby & J.W.Grimes) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 62,
    "inputRank": "",
    "inputName": "Abarema jupunba",
    "matchType": "variant",
    "ID": "h4jGkCtKNaf07dRMspslJ",
    "rank": "species",
    "label": "Abarema jupunba (Willd.) Britton & Killip",
    "scientificName": "Abarema jupunba",
    "authorship": "(Willd.) Britton & Killip",
    "status": "synonym",
    "acceptedName": "Jupunba trapezifolia var. micradenia (Benth.) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "VARIETY:Jupunba trapezifolia var. micradenia (Benth.) M.V.B.Soares, M.P.Morim & Iganci|SPECIES:Jupunba trapezifolia (Vahl) Moldenke|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 63,
    "inputRank": "",
    "inputName": "Abarema laeta",
    "matchType": "variant",
    "ID": "BUQSvsYFyh7T18v3Y_OpU0",
    "rank": "species",
    "label": "Abarema laeta (Benth.) Barneby & J.W.Grimes",
    "scientificName": "Abarema laeta",
    "authorship": "(Benth.) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba laeta (Benth.) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba laeta (Benth.) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 64,
    "inputRank": "",
    "inputName": "Abarema leucophylla",
    "matchType": "variant",
    "ID": "zPm1np9pYb8oAKjanKg0h",
    "rank": "species",
    "label": "Abarema leucophylla (Spruce ex Benth.) Barneby & J.W.Grimes",
    "scientificName": "Abarema leucophylla",
    "authorship": "(Spruce ex Benth.) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba leucophylla (Spruce ex Benth.) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba leucophylla (Spruce ex Benth.) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 65,
    "inputRank": "",
    "inputName": "Abarema macradenia",
    "matchType": "variant",
    "ID": "qTmopQw_cnteCpSYGTXw40",
    "rank": "species",
    "label": "Abarema macradenia (Pittier) Barneby & J.W.Grimes",
    "scientificName": "Abarema macradenia",
    "authorship": "(Pittier) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba macradenia (Pittier) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba macradenia (Pittier) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 66,
    "inputRank": "",
    "inputName": "Abarema maestrensis",
    "matchType": "variant",
    "ID": "SP3WeGqLEA92AlBsqGA-g",
    "rank": "species",
    "label": "Abarema maestrensis (Urb.) Bässler",
    "scientificName": "Abarema maestrensis",
    "authorship": "(Urb.) Bässler",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abarema Pittier|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 67,
    "inputRank": "",
    "inputName": "Abarema nipensis",
    "matchType": "variant",
    "ID": "7EKkhAW5sbtc-OQ6Z00PT0",
    "rank": "species",
    "label": "Abarema nipensis (Britton) Barneby & J.W.Grimes",
    "scientificName": "Abarema nipensis",
    "authorship": "(Britton) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba nipensis (Britton) Britton & Rose",
    "classification": "SPECIES:Jupunba nipensis (Britton) Britton & Rose|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 68,
    "inputRank": "",
    "inputName": "Abarema oxyphyllidia",
    "matchType": "variant",
    "ID": "wWTSsVwmR0AP0_11w-vDz0",
    "rank": "species",
    "label": "Abarema oxyphyllidia Barneby & J.W.Grimes",
    "scientificName": "Abarema oxyphyllidia",
    "authorship": "Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba oxyphyllidia (Barneby & J.W.Grimes) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba oxyphyllidia (Barneby & J.W.Grimes) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 69,
    "inputRank": "",
    "inputName": "Abarema villifera",
    "matchType": "variant",
    "ID": "bdDLMxPIub7u8K9cLUytN0",
    "rank": "species",
    "label": "Abarema villifera (Ducke) Barneby & J.W.Grimes",
    "scientificName": "Abarema villifera",
    "authorship": "(Ducke) Barneby & J.W.Grimes",
    "status": "synonym",
    "acceptedName": "Jupunba villifera (Ducke) M.V.B.Soares, M.P.Morim & Iganci",
    "classification": "SPECIES:Jupunba villifera (Ducke) M.V.B.Soares, M.P.Morim & Iganci|GENUS:Jupunba Britton & Rose|FAMILY:Fabaceae|ORDER:Fabales Bromhead|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 70,
    "inputRank": "",
    "inputName": "Abatia americana",
    "matchType": "variant",
    "ID": "Hgsps3snnYQb9hepgL4yq1",
    "rank": "species",
    "label": "Abatia americana (Gardner) Eichler",
    "scientificName": "Abatia americana",
    "authorship": "(Gardner) Eichler",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abatia Ruiz & Pav.|FAMILY:Salicaceae Mirb.|ORDER:Malpighiales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 71,
    "inputRank": "",
    "inputName": "Abatia glabra",
    "matchType": "variant",
    "ID": "uDG3lo3mOHdUCpOk5v2U1",
    "rank": "species",
    "label": "Abatia glabra Sleumer",
    "scientificName": "Abatia glabra",
    "authorship": "Sleumer",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abatia Ruiz & Pav.|FAMILY:Salicaceae Mirb.|ORDER:Malpighiales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 72,
    "inputRank": "",
    "inputName": "Abatia rugosa",
    "matchType": "variant",
    "ID": "8_UtE2oZA0v7C4APQch8B1",
    "rank": "species",
    "label": "Abatia rugosa Ruiz & Pav.",
    "scientificName": "Abatia rugosa",
    "authorship": "Ruiz & Pav.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abatia Ruiz & Pav.|FAMILY:Salicaceae Mirb.|ORDER:Malpighiales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 73,
    "inputRank": "",
    "inputName": "Abelia",
    "matchType": "variant",
    "ID": "DIAOdF0VHucc90hs_fkUI0",
    "rank": "genus",
    "label": "Abelia R. Br.",
    "scientificName": "Abelia",
    "authorship": "R. Br.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SUBFAMILY:Linnaeoideae Raf.|FAMILY:Caprifoliaceae Juss.|ORDER:Dipsacales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 74,
    "inputRank": "",
    "inputName": "Abelia chinensis",
    "matchType": "variant",
    "ID": "K0FvBPBmtpcBCxk1ote9A0",
    "rank": "species",
    "label": "Abelia chinensis R. Br.",
    "scientificName": "Abelia chinensis",
    "authorship": "R. Br.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abelia R. Br.|SUBFAMILY:Linnaeoideae Raf.|FAMILY:Caprifoliaceae Juss.|ORDER:Dipsacales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 75,
    "inputRank": "",
    "inputName": "Abelia engleriana",
    "matchType": "variant",
    "ID": "r4vqKWgz48cFBpH8k2jmq1",
    "rank": "species",
    "label": "Abelia engleriana (Graebn.) Rehder",
    "scientificName": "Abelia engleriana",
    "authorship": "(Graebn.) Rehder",
    "status": "synonym",
    "acceptedName": "Abelia macrotera var. engleriana (Graebn.) Landrein",
    "classification": "VARIETY:Abelia macrotera var. engleriana (Graebn.) Landrein|SPECIES:Abelia macrotera (Graebn. & Buchw.) Rehder|GENUS:Abelia R. Br.|SUBFAMILY:Linnaeoideae Raf.|FAMILY:Caprifoliaceae Juss.|ORDER:Dipsacales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 76,
    "inputRank": "",
    "inputName": "Abelia macrotera (Graebn. Et Buchw.) Rehd.",
    "matchType": "variant",
    "ID": "SCvL400UMudfDpgDV9EbU0",
    "rank": "species",
    "label": "Abelia macrotera (Graebn. & Buchw.) Rehder",
    "scientificName": "Abelia macrotera",
    "authorship": "(Graebn. & Buchw.) Rehder",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abelia R. Br.|SUBFAMILY:Linnaeoideae Raf.|FAMILY:Caprifoliaceae Juss.|ORDER:Dipsacales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 77,
    "inputRank": "",
    "inputName": "Abelia sp",
    "matchType": "variant",
    "ID": "DIAOdF0VHucc90hs_fkUI0",
    "rank": "genus",
    "label": "Abelia R. Br.",
    "scientificName": "Abelia",
    "authorship": "R. Br.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SUBFAMILY:Linnaeoideae Raf.|FAMILY:Caprifoliaceae Juss.|ORDER:Dipsacales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "INDETERMINED"
  },
  {
    "inputID": 78,
    "inputRank": "",
    "inputName": "Abelia uniflora",
    "matchType": "variant",
    "ID": "4tTnTY3mlF920GHk2pFR-1",
    "rank": "species",
    "label": "Abelia uniflora R. Br.",
    "scientificName": "Abelia uniflora",
    "authorship": "R. Br.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abelia R. Br.|SUBFAMILY:Linnaeoideae Raf.|FAMILY:Caprifoliaceae Juss.|ORDER:Dipsacales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 79,
    "inputRank": "",
    "inputName": "Abelia_xgrandiflora",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 80,
    "inputRank": "",
    "inputName": "Abelmoschus",
    "matchType": "variant",
    "ID": "I1im3Xq0jTf24xzW-GDKr2",
    "rank": "genus",
    "label": "Abelmoschus Medik.",
    "scientificName": "Abelmoschus",
    "authorship": "Medik.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SUBFAMILY:Malvoideae Burnett|FAMILY:Malvaceae Juss.|ORDER:Malvales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 81,
    "inputRank": "",
    "inputName": "Abelmoschus esculentus",
    "matchType": "variant",
    "ID": "joaWuR8_2GAe9_JLZgiLH2",
    "rank": "species",
    "label": "Abelmoschus esculentus (L.) Moench",
    "scientificName": "Abelmoschus esculentus",
    "authorship": "(L.) Moench",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abelmoschus Medik.|SUBFAMILY:Malvoideae Burnett|FAMILY:Malvaceae Juss.|ORDER:Malvales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 82,
    "inputRank": "",
    "inputName": "Abelmoschus ficulneus (L.) Wight & Arn.",
    "matchType": "variant",
    "ID": "cQRVMr08yX7eACzSq_li_1",
    "rank": "species",
    "label": "Abelmoschus ficulneus (L.) Wight & Arn. ex Wight",
    "scientificName": "Abelmoschus ficulneus",
    "authorship": "(L.) Wight & Arn. ex Wight",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abelmoschus Medik.|SUBFAMILY:Malvoideae Burnett|FAMILY:Malvaceae Juss.|ORDER:Malvales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 83,
    "inputRank": "",
    "inputName": "Abelmoschus moschatus",
    "matchType": "variant",
    "ID": "kW_mJEewg-dN98FKWg1lC2",
    "rank": "species",
    "label": "Abelmoschus moschatus (L.) Medik.",
    "scientificName": "Abelmoschus moschatus",
    "authorship": "(L.) Medik.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abelmoschus Medik.|SUBFAMILY:Malvoideae Burnett|FAMILY:Malvaceae Juss.|ORDER:Malvales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 84,
    "inputRank": "",
    "inputName": "Abelmoshus esculentus (L.) Moench",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 85,
    "inputRank": "",
    "inputName": "Abies  faxoniana",
    "matchType": "variant",
    "ID": "ZYxIqzF2_kPA7lDlet4Sw2",
    "rank": "species",
    "label": "Abies faxoniana Rehder & E.H.Wilson",
    "scientificName": "Abies faxoniana",
    "authorship": "Rehder & E.H.Wilson",
    "status": "synonym",
    "acceptedName": "Abies fargesii var. faxoniana (Rehder & E.H.Wilson) Tang S.Liu",
    "classification": "VARIETY:Abies fargesii var. faxoniana (Rehder & E.H.Wilson) Tang S.Liu|SPECIES:Abies fargesii Franch.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 86,
    "inputRank": "",
    "inputName": "Abies ?shastensis (Lemmon) Lemmon [magnifica ? procera]",
    "matchType": "variant",
    "ID": "oJcwu0yVYcvx58sykTyha1",
    "rank": "genus",
    "label": "Abies Mill.",
    "scientificName": "Abies",
    "authorship": "Mill.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "PARTIALLY_PARSABLE_NAME"
  },
  {
    "inputID": 87,
    "inputRank": "",
    "inputName": "Abies amabilis (Douglas ex Louden) Douglas ex Forbes",
    "matchType": "variant",
    "ID": "OF3ByWuRequZ28R-PwNya0",
    "rank": "species",
    "label": "Abies amabilis (Douglas ex Loudon) J.Forbes",
    "scientificName": "Abies amabilis",
    "authorship": "(Douglas ex Loudon) J.Forbes",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 88,
    "inputRank": "",
    "inputName": "Abies balsamea (L.) Mill. var. balsamea",
    "matchType": "variant",
    "ID": "2NOu3wWzmdQI3SwP5se0O0",
    "rank": "form",
    "label": "Abies balsamea f. balsamea",
    "scientificName": "Abies balsamea f. balsamea",
    "authorship": "",
    "status": "synonym",
    "acceptedName": "Abies balsamea (L.) Mill.",
    "classification": "SPECIES:Abies balsamea (L.) Mill.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 89,
    "inputRank": "",
    "inputName": "Abies beshanzuensis",
    "matchType": "variant",
    "ID": "-GjhCunoKTNJAGjLYAvvE0",
    "rank": "species",
    "label": "Abies beshanzuensis M.H.Wu",
    "scientificName": "Abies beshanzuensis",
    "authorship": "M.H.Wu",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 90,
    "inputRank": "",
    "inputName": "Abies bornmuelleriana",
    "matchType": "variant",
    "ID": "Tt8WiVVFdGdl8lAbUI5Ic",
    "rank": "species",
    "label": "Abies bornmuelleriana Mattf.",
    "scientificName": "Abies bornmuelleriana",
    "authorship": "Mattf.",
    "status": "synonym",
    "acceptedName": "Abies nordmanniana subsp. equi-trojani (Asch. & Sint. ex Boiss.) Coode & Cullen",
    "classification": "SUBSPECIES:Abies nordmanniana subsp. equi-trojani (Asch. & Sint. ex Boiss.) Coode & Cullen|SPECIES:Abies nordmanniana (Steven) Spach|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 91,
    "inputRank": "",
    "inputName": "Abies cephalonica J. W. Loudon",
    "matchType": "variant",
    "ID": "-uqeYbsE1Qvk-pcGiAf4G0",
    "rank": "species",
    "label": "Abies cephalonica Loudon",
    "scientificName": "Abies cephalonica",
    "authorship": "Loudon",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 92,
    "inputRank": "",
    "inputName": "Abies chensiensis",
    "matchType": "variant",
    "ID": "g04zL4-W_mAz3WpxInZ-R2",
    "rank": "species",
    "label": "Abies chensiensis Tiegh.",
    "scientificName": "Abies chensiensis",
    "authorship": "Tiegh.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 93,
    "inputRank": "",
    "inputName": "Abies cilicica (Antoine & Kotschy) Carriere ssp. isaurica Coode & Cullen",
    "matchType": "variant",
    "ID": "_LbUU7XXarej2OZLEWyC21",
    "rank": "subspecies",
    "label": "Abies cilicica subsp. isaurica Coode & Cullen",
    "scientificName": "Abies cilicica subsp. isaurica",
    "authorship": "Coode & Cullen",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abies cilicica (Antoine & Kotschy) Carrière|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 94,
    "inputRank": "",
    "inputName": "Abies concolor (Gordon & Glend.) Lindl. ex Hildebr.",
    "matchType": "variant",
    "ID": "yNGZP9I-z2A3CSDwtcQi-0",
    "rank": "species",
    "label": "Abies concolor (Gordon) Lindl. ex Hildebr.",
    "scientificName": "Abies concolor",
    "authorship": "(Gordon) Lindl. ex Hildebr.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 95,
    "inputRank": "",
    "inputName": "Abies concolor ssp. concolor",
    "matchType": "variant",
    "ID": "Nv6kf5Sr-Afe6CeHm2-LC0",
    "rank": "variety",
    "label": "Abies concolor var. concolor",
    "scientificName": "Abies concolor var. concolor",
    "authorship": "",
    "status": "synonym",
    "acceptedName": "Abies concolor (Gordon) Lindl. ex Hildebr.",
    "classification": "SPECIES:Abies concolor (Gordon) Lindl. ex Hildebr.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 96,
    "inputRank": "",
    "inputName": "Abies delavayi Franch.",
    "matchType": "exact",
    "ID": "L8Q6ZpzWzddW70ySlPf6n2",
    "rank": "species",
    "label": "Abies delavayi Franch.",
    "scientificName": "Abies delavayi",
    "authorship": "Franch.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 97,
    "inputRank": "",
    "inputName": "Abies ernestii",
    "matchType": "variant",
    "ID": "qmjZpKXlpssdDC89W2fZX1",
    "rank": "species",
    "label": "Abies ernestii Rehder",
    "scientificName": "Abies ernestii",
    "authorship": "Rehder",
    "status": "synonym",
    "acceptedName": "Abies recurvata var. ernestii (Rehder) Rushforth",
    "classification": "VARIETY:Abies recurvata var. ernestii (Rehder) Rushforth|SPECIES:Abies recurvata Mast.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 98,
    "inputRank": "",
    "inputName": "Abies fabri (Mast.) Craib",
    "matchType": "exact",
    "ID": "BC0a4W_TTbuv60xh_2IWL0",
    "rank": "species",
    "label": "Abies fabri (Mast.) Craib",
    "scientificName": "Abies fabri",
    "authorship": "(Mast.) Craib",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 99,
    "inputRank": "",
    "inputName": "Abies ferreana",
    "matchType": "variant",
    "ID": "U6Yw67urVY8O8pTd8e0Ox1",
    "rank": "species",
    "label": "Abies ferreana Bordères & Gaussen",
    "scientificName": "Abies ferreana",
    "authorship": "Bordères & Gaussen",
    "status": "synonym",
    "acceptedName": "Abies forrestii var. ferreana (Bordères & Gaussen) Farjon & Silba",
    "classification": "VARIETY:Abies forrestii var. ferreana (Bordères & Gaussen) Farjon & Silba|SPECIES:Abies forrestii Coltm.-Rog.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 100,
    "inputRank": "",
    "inputName": "Abies flinckii",
    "matchType": "variant",
    "ID": "RcrbjMDUoFAa94ScIqglG1",
    "rank": "species",
    "label": "Abies flinckii Rushforth",
    "scientificName": "Abies flinckii",
    "authorship": "Rushforth",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 101,
    "inputRank": "",
    "inputName": "Abies fraseri",
    "matchType": "variant",
    "ID": "m_0u2Lx-z-v50GhESoZk10",
    "rank": "species",
    "label": "Abies fraseri (Pursh) Poir.",
    "scientificName": "Abies fraseri",
    "authorship": "(Pursh) Poir.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 102,
    "inputRank": "",
    "inputName": "Abies grandis",
    "matchType": "variant",
    "ID": "kp8OG_WDXxPDBKB_PR0UD0",
    "rank": "species",
    "label": "Abies grandis (Douglas ex D.Don) Lindl.",
    "scientificName": "Abies grandis",
    "authorship": "(Douglas ex D.Don) Lindl.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 103,
    "inputRank": "",
    "inputName": "Abies guatemalensis",
    "matchType": "variant",
    "ID": "njcsPsDMRkQrEW4MBprq50",
    "rank": "species",
    "label": "Abies guatemalensis Rehder",
    "scientificName": "Abies guatemalensis",
    "authorship": "Rehder",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 104,
    "inputRank": "",
    "inputName": "Abies homolepis",
    "matchType": "variant",
    "ID": "f8CeNU0xx2Ae5Sp13tcfB2",
    "rank": "species",
    "label": "Abies homolepis Siebold & Zucc.",
    "scientificName": "Abies homolepis",
    "authorship": "Siebold & Zucc.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 105,
    "inputRank": "",
    "inputName": "Abies jaliscana",
    "matchType": "variant",
    "ID": "UfZnPJ41RQOcD42UufUA70",
    "rank": "species",
    "label": "Abies jaliscana (Martínez) Mantilla, Shalisko & A.Vázquez",
    "scientificName": "Abies jaliscana",
    "authorship": "(Martínez) Mantilla, Shalisko & A.Vázquez",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 106,
    "inputRank": "",
    "inputName": "Abies koreana E.H.Wilson",
    "matchType": "exact",
    "ID": "pyftbIMhNvQ878jgWcwsI2",
    "rank": "species",
    "label": "Abies koreana E.H.Wilson",
    "scientificName": "Abies koreana",
    "authorship": "E.H.Wilson",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 107,
    "inputRank": "",
    "inputName": "Abies lasiocarpa var. arizonica",
    "matchType": "variant",
    "ID": "xyVqGYp553AbDx2shAlun2",
    "rank": "variety",
    "label": "Abies lasiocarpa var. arizonica (Merriam) Lemmon",
    "scientificName": "Abies lasiocarpa var. arizonica",
    "authorship": "(Merriam) Lemmon",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abies lasiocarpa (Hook.) Nutt.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 108,
    "inputRank": "",
    "inputName": "Abies magnifica A. Murray",
    "matchType": "variant",
    "ID": "WkMAPkQs1sAj6xL2_fzbj2",
    "rank": "species",
    "label": "Abies magnifica A.Murray bis",
    "scientificName": "Abies magnifica",
    "authorship": "A.Murray bis",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 109,
    "inputRank": "",
    "inputName": "Abies magnifica A.Murray var. shastensis Lemmon",
    "matchType": "variant",
    "ID": "Let5Vm5GKVvIC8lxVrxrE",
    "rank": "variety",
    "label": "Abies magnifica var. shastensis Lemmon",
    "scientificName": "Abies magnifica var. shastensis",
    "authorship": "Lemmon",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abies magnifica A.Murray bis|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 110,
    "inputRank": "",
    "inputName": "Abies marocana",
    "matchType": "variant",
    "ID": "9mYR7vFU1K9Q5lFqYt70F0",
    "rank": "species",
    "label": "Abies marocana Trab.",
    "scientificName": "Abies marocana",
    "authorship": "Trab.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 111,
    "inputRank": "",
    "inputName": "Abies nephrolepis (Trautv.) Maxim",
    "matchType": "variant",
    "ID": "enOHXselt97780TytM5Cv2",
    "rank": "species",
    "label": "Abies nephrolepis (Trautv. ex Maxim.) Maxim.",
    "scientificName": "Abies nephrolepis",
    "authorship": "(Trautv. ex Maxim.) Maxim.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 112,
    "inputRank": "",
    "inputName": "Abies nordmanniana (Steven) Spach subsp. nordmanniana",
    "matchType": "variant",
    "ID": "QsRvNnkQnFd55KaVoIw_Z1",
    "rank": "subspecies",
    "label": "Abies nordmanniana subsp. nordmanniana",
    "scientificName": "Abies nordmanniana subsp. nordmanniana",
    "authorship": "",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abies nordmanniana (Steven) Spach|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 113,
    "inputRank": "",
    "inputName": "Abies numidica",
    "matchType": "variant",
    "ID": "oDRpyaZCENOs14CZ4Wfrl1",
    "rank": "species",
    "label": "Abies numidica de Lannoy ex Carrière",
    "scientificName": "Abies numidica",
    "authorship": "de Lannoy ex Carrière",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 114,
    "inputRank": "",
    "inputName": "Abies phanerolepis",
    "matchType": "variant",
    "ID": "kMqBLdDvjZeY0WtjPYYAB1",
    "rank": "species",
    "label": "Abies phanerolepis (Fernald) T.S.Liu",
    "scientificName": "Abies phanerolepis",
    "authorship": "(Fernald) T.S.Liu",
    "status": "synonym",
    "acceptedName": "Abies balsamea var. phanerolepis Fernald",
    "classification": "VARIETY:Abies balsamea var. phanerolepis Fernald|SPECIES:Abies balsamea (L.) Mill.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 115,
    "inputRank": "",
    "inputName": "Abies pinsapo Boiss. var. glauca",
    "matchType": "variant",
    "ID": "eg3kETuVI7sH5OxlnHTTw1",
    "rank": "form",
    "label": "Abies pinsapo f. glauca (Carrière) Beissn.",
    "scientificName": "Abies pinsapo f. glauca",
    "authorship": "(Carrière) Beissn.",
    "status": "synonym",
    "acceptedName": "Abies pinsapo Boiss.",
    "classification": "SPECIES:Abies pinsapo Boiss.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 116,
    "inputRank": "",
    "inputName": "Abies recurvata",
    "matchType": "variant",
    "ID": "g87NAFKLrpO-9pfZbgvWg1",
    "rank": "species",
    "label": "Abies recurvata Mast.",
    "scientificName": "Abies recurvata",
    "authorship": "Mast.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 117,
    "inputRank": "",
    "inputName": "Abies religiosa (Kunth) Schltdl. & Cham. var. emarginata",
    "matchType": "variant",
    "ID": "fXYOEmIBYQt83_9Z9LkKa",
    "rank": "variety",
    "label": "Abies religiosa var. emarginata Loock & Martínez ex Martínez",
    "scientificName": "Abies religiosa var. emarginata",
    "authorship": "Loock & Martínez ex Martínez",
    "status": "synonym",
    "acceptedName": "Abies jaliscana (Martínez) Mantilla, Shalisko & A.Vázquez",
    "classification": "SPECIES:Abies jaliscana (Martínez) Mantilla, Shalisko & A.Vázquez|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 118,
    "inputRank": "",
    "inputName": "Abies sachalinensis (F.Schmidt) Mast. var. mayriana Miyabe & Kud?",
    "matchType": "variant",
    "ID": "_giKXaYvRXQK7tWDcPFlD",
    "rank": "variety",
    "label": "Abies sachalinensis var. mayriana Miyabe & Kudô",
    "scientificName": "Abies sachalinensis var. mayriana",
    "authorship": "Miyabe & Kudô",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abies sachalinensis (F.Schmidt) Mast.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "UNUSUAL_NAME_CHARACTERS;DOUBTFUL_NAME;PARTIALLY_PARSABLE_NAME"
  },
  {
    "inputID": 119,
    "inputRank": "",
    "inputName": "Abies shastensis",
    "matchType": "variant",
    "ID": "Ly1NqfaWLnNIAKCLScDR8",
    "rank": "species",
    "label": "Abies shastensis Lemmon",
    "scientificName": "Abies shastensis",
    "authorship": "Lemmon",
    "status": "synonym",
    "acceptedName": "Abies magnifica var. shastensis Lemmon",
    "classification": "VARIETY:Abies magnifica var. shastensis Lemmon|SPECIES:Abies magnifica A.Murray bis|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 120,
    "inputRank": "",
    "inputName": "Abies sp",
    "matchType": "variant",
    "ID": "oJcwu0yVYcvx58sykTyha1",
    "rank": "genus",
    "label": "Abies Mill.",
    "scientificName": "Abies",
    "authorship": "Mill.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "INDETERMINED"
  },
  {
    "inputID": 121,
    "inputRank": "",
    "inputName": "Abies spectabilis (D. Don) Spach",
    "matchType": "exact",
    "ID": "ToHQ5fFUpXAq2_OqLumUq0",
    "rank": "species",
    "label": "Abies spectabilis (D.Don) Spach",
    "scientificName": "Abies spectabilis",
    "authorship": "(D.Don) Spach",
    "status": "synonym",
    "acceptedName": "Abies spectabilis (D.Don) Mirb.",
    "classification": "SPECIES:Abies spectabilis (D.Don) Mirb.|GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 122,
    "inputRank": "",
    "inputName": "Abies veitchii",
    "matchType": "variant",
    "ID": "keI9YqXVQSsZ90B2ySIwT1",
    "rank": "species",
    "label": "Abies veitchii Lindl.",
    "scientificName": "Abies veitchii",
    "authorship": "Lindl.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 123,
    "inputRank": "",
    "inputName": "Abies vejarii Mart?nez",
    "matchType": "variant",
    "ID": "WMLE2QBuP7fp4_6OnR0LF2",
    "rank": "species",
    "label": "Abies vejarii Martínez",
    "scientificName": "Abies vejarii",
    "authorship": "Martínez",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "UNUSUAL_NAME_CHARACTERS;DOUBTFUL_NAME;PARTIALLY_PARSABLE_NAME"
  },
  {
    "inputID": 124,
    "inputRank": "",
    "inputName": "Abies ziyuanensis",
    "matchType": "variant",
    "ID": "PjaHyLQMU6A9ExGIRygww2",
    "rank": "species",
    "label": "Abies ziyuanensis L.K.Fu & S.L.Mo",
    "scientificName": "Abies ziyuanensis",
    "authorship": "L.K.Fu & S.L.Mo",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abies Mill.|FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 125,
    "inputRank": "",
    "inputName": "Abies?spectabilis?(D.?Don)?Mirbel",
    "matchType": "variant",
    "ID": "oJcwu0yVYcvx58sykTyha1",
    "rank": "genus",
    "label": "Abies Mill.",
    "scientificName": "Abies",
    "authorship": "Mill.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "FAMILY:Pinaceae Spreng. ex Rudolphi|ORDER:Pinales Gorozh.|SUBCLASS:Pinidae Cronquist, Takht. & W.Zimm.|CLASS:Pinopsida Burnett|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "UNUSUAL_NAME_CHARACTERS;DOUBTFUL_NAME;PARTIALLY_PARSABLE_NAME"
  },
  {
    "inputID": 126,
    "inputRank": "",
    "inputName": "Abies_religiosa_AJU",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 127,
    "inputRank": "",
    "inputName": "Abildgaardia abortiva (Steud.) Lye",
    "matchType": "exact",
    "ID": "zSbfadWi0dcmEWKGsHW8e0",
    "rank": "species",
    "label": "Abildgaardia abortiva (Steud.) Lye",
    "scientificName": "Abildgaardia abortiva",
    "authorship": "(Steud.) Lye",
    "status": "synonym",
    "acceptedName": "Bulbostylis abortiva (Steud.) C.B.Clarke",
    "classification": "SPECIES:Bulbostylis abortiva (Steud.) C.B.Clarke|GENUS:Bulbostylis Kunth|FAMILY:Cyperaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 128,
    "inputRank": "",
    "inputName": "Abildgaardia coleotricha",
    "matchType": "variant",
    "ID": "xyG2XpX7eq9C00Yy9GRf12",
    "rank": "species",
    "label": "Abildgaardia coleotricha (Hochst. ex A.Rich.) Lye",
    "scientificName": "Abildgaardia coleotricha",
    "authorship": "(Hochst. ex A.Rich.) Lye",
    "status": "synonym",
    "acceptedName": "Bulbostylis coleotricha (Hochst. ex A.Rich.) C.B.Clarke",
    "classification": "SPECIES:Bulbostylis coleotricha (Hochst. ex A.Rich.) C.B.Clarke|GENUS:Bulbostylis Kunth|FAMILY:Cyperaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 129,
    "inputRank": "",
    "inputName": "Abildgaardia natalensis",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 130,
    "inputRank": "",
    "inputName": "Abildgaardia polygama",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 131,
    "inputRank": "",
    "inputName": "Abiu caramuri",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 132,
    "inputRank": "",
    "inputName": "ABIURANA",
    "matchType": "none",
    "ID": "",
    "rank": "",
    "label": "",
    "scientificName": "",
    "authorship": "",
    "status": "",
    "acceptedName": "",
    "classification": "",
    "issues": ""
  },
  {
    "inputID": 133,
    "inputRank": "",
    "inputName": "Abolboda americana",
    "matchType": "variant",
    "ID": "VvrYN3NRe0968xYIeKZNx2",
    "rank": "species",
    "label": "Abolboda americana (Aubl.) Lanj.",
    "scientificName": "Abolboda americana",
    "authorship": "(Aubl.) Lanj.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abolboda Bonpl.|FAMILY:Xyridaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 134,
    "inputRank": "",
    "inputName": "Abolboda egleri",
    "matchType": "variant",
    "ID": "9nZ3AIx2yPugAh8NVQ3R61",
    "rank": "species",
    "label": "Abolboda egleri L.B.Sm. & Downs",
    "scientificName": "Abolboda egleri",
    "authorship": "L.B.Sm. & Downs",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abolboda Bonpl.|FAMILY:Xyridaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 135,
    "inputRank": "",
    "inputName": "Abolboda linearifolia",
    "matchType": "variant",
    "ID": "Ob8SRpTDeAA67S235ddqU",
    "rank": "species",
    "label": "Abolboda linearifolia Maguire",
    "scientificName": "Abolboda linearifolia",
    "authorship": "Maguire",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abolboda Bonpl.|FAMILY:Xyridaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 136,
    "inputRank": "",
    "inputName": "Abolboda poarchon Seub.",
    "matchType": "exact",
    "ID": "9OPu2_VR9k9F6pp5N-Jbb",
    "rank": "species",
    "label": "Abolboda poarchon Seub.",
    "scientificName": "Abolboda poarchon",
    "authorship": "Seub.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abolboda Bonpl.|FAMILY:Xyridaceae|ORDER:Poales|CLASS:Liliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 137,
    "inputRank": "",
    "inputName": "Abortopetalum sandwicense",
    "matchType": "variant",
    "ID": "FDJwMSbun3766Guys9Pdp",
    "rank": "species",
    "label": "Abortopetalum sandwicense O. Deg.",
    "scientificName": "Abortopetalum sandwicense",
    "authorship": "O. Deg.",
    "status": "synonym",
    "acceptedName": "Abutilon sandwicense (O. Deg.) Christoph.",
    "classification": "SPECIES:Abutilon sandwicense (O. Deg.) Christoph.|GENUS:Abutilon Tourn. ex Mill.|SUBFAMILY:Malvoideae Burnett|FAMILY:Malvaceae Juss.|ORDER:Malvales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 138,
    "inputRank": "",
    "inputName": "Abrahamia grandidieri",
    "matchType": "variant",
    "ID": "2m8MPsZBToNl6hX_SW5bE1",
    "rank": "species",
    "label": "Abrahamia grandidieri (Engl.) Randrian. & Lowry",
    "scientificName": "Abrahamia grandidieri",
    "authorship": "(Engl.) Randrian. & Lowry",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrahamia Randrian. & Lowry|FAMILY:Anacardiaceae R. Br.|ORDER:Sapindales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 139,
    "inputRank": "",
    "inputName": "Abrahamia louvelii",
    "matchType": "variant",
    "ID": "KrgiAF_9X7ez8KuHpodHA2",
    "rank": "species",
    "label": "Abrahamia louvelii (H. Perrier) Randrian. & Lowry",
    "scientificName": "Abrahamia louvelii",
    "authorship": "(H. Perrier) Randrian. & Lowry",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrahamia Randrian. & Lowry|FAMILY:Anacardiaceae R. Br.|ORDER:Sapindales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 140,
    "inputRank": "",
    "inputName": "Abrahamia thouvenotii",
    "matchType": "variant",
    "ID": "_VyZ4wqBqKeY74n79ac9_2",
    "rank": "species",
    "label": "Abrahamia thouvenotii (Lecomte) Randrian. & Lowry",
    "scientificName": "Abrahamia thouvenotii",
    "authorship": "(Lecomte) Randrian. & Lowry",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrahamia Randrian. & Lowry|FAMILY:Anacardiaceae R. Br.|ORDER:Sapindales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 141,
    "inputRank": "",
    "inputName": "Abrodictyum cupressoides",
    "matchType": "variant",
    "ID": "2uLocATlEIdJ4dS1ThcDC1",
    "rank": "species",
    "label": "Abrodictyum cupressoides (Desv.) Ebihara & Dubuisson",
    "scientificName": "Abrodictyum cupressoides",
    "authorship": "(Desv.) Ebihara & Dubuisson",
    "status": "synonym",
    "acceptedName": "Trichomanes cupressoides Desv.",
    "classification": "SPECIES:Trichomanes cupressoides Desv.|GENUS:Trichomanes L.|SUBFAMILY:Trichomanoideae C.Presl|FAMILY:Hymenophyllaceae Mart.|ORDER:Hymenophyllales A.B.Frank|CLASS:Polypodiopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 142,
    "inputRank": "",
    "inputName": "Abroma augusta",
    "matchType": "variant",
    "ID": "lMc-Zdw-gIto-dDmeMCaO0",
    "rank": "species",
    "label": "Abroma augustum (L.) L. fil.",
    "scientificName": "Abroma augustum",
    "authorship": "(L.) L. fil.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abroma L.f.|SUBFAMILY:Byttnerioideae Burnett|FAMILY:Malvaceae Juss.|ORDER:Malvales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 143,
    "inputRank": "",
    "inputName": "Abronia × minor",
    "matchType": "variant",
    "ID": "762P_d5oVKfv8_oq7jYph1",
    "rank": "species",
    "label": "Abronia × minor Standl.",
    "scientificName": "Abronia × minor",
    "authorship": "Standl.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 144,
    "inputRank": "",
    "inputName": "Abronia ameliae Lundell",
    "matchType": "exact",
    "ID": "tykvIegyhesA5O0ncvpL30",
    "rank": "species",
    "label": "Abronia ameliae Lundell",
    "scientificName": "Abronia ameliae",
    "authorship": "Lundell",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 145,
    "inputRank": "",
    "inputName": "Abronia bolackii",
    "matchType": "variant",
    "ID": "jq-KePU8-hOI6OXJqSDs4",
    "rank": "species",
    "label": "Abronia bolackii N. D. Atwood, S. L. Welsh & K. D. Heil",
    "scientificName": "Abronia bolackii",
    "authorship": "N. D. Atwood, S. L. Welsh & K. D. Heil",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 146,
    "inputRank": "",
    "inputName": "Abronia cycloptera",
    "matchType": "variant",
    "ID": "IdGsSwfyflt024_au9KOk1",
    "rank": "species",
    "label": "Abronia cycloptera A. Gray",
    "scientificName": "Abronia cycloptera",
    "authorship": "A. Gray",
    "status": "synonym",
    "acceptedName": "Tripterocalyx micranthus (Torr.) Hook.",
    "classification": "SPECIES:Tripterocalyx micranthus (Torr.) Hook.|GENUS:Tripterocalyx (Torr.) Hook.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 147,
    "inputRank": "",
    "inputName": "Abronia fragrans Nutt. ex Hook.",
    "matchType": "exact",
    "ID": "0GEGBaiJkRc16l720FRyS",
    "rank": "species",
    "label": "Abronia fragrans Nutt. ex Hook.",
    "scientificName": "Abronia fragrans",
    "authorship": "Nutt. ex Hook.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 148,
    "inputRank": "",
    "inputName": "Abronia latifolia",
    "matchType": "variant",
    "ID": "rX0iWcCIN17138qMk2Wq7",
    "rank": "species",
    "label": "Abronia latifolia Eschsch.",
    "scientificName": "Abronia latifolia",
    "authorship": "Eschsch.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 149,
    "inputRank": "",
    "inputName": "Abronia mellifera",
    "matchType": "variant",
    "ID": "qJ9pJE_8yXtT5tMzs74Px1",
    "rank": "species",
    "label": "Abronia mellifera Douglas",
    "scientificName": "Abronia mellifera",
    "authorship": "Douglas",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 150,
    "inputRank": "",
    "inputName": "Abronia nana S.Watson",
    "matchType": "exact",
    "ID": "ASZ6E_LzGosc5py2UQqLL1",
    "rank": "species",
    "label": "Abronia nana S. Watson",
    "scientificName": "Abronia nana",
    "authorship": "S. Watson",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 151,
    "inputRank": "",
    "inputName": "Abronia orbiculata",
    "matchType": "variant",
    "ID": "vEtredQykwPZ2WKvJxogS2",
    "rank": "species",
    "label": "Abronia orbiculata Standl.",
    "scientificName": "Abronia orbiculata",
    "authorship": "Standl.",
    "status": "synonym",
    "acceptedName": "Abronia turbinata Torr. ex S. Watson",
    "classification": "SPECIES:Abronia turbinata Torr. ex S. Watson|GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 152,
    "inputRank": "",
    "inputName": "Abronia pumila",
    "matchType": "variant",
    "ID": "Yb1TdisQtwdp7G7zgJuBP",
    "rank": "species",
    "label": "Abronia pumila Rydb.",
    "scientificName": "Abronia pumila",
    "authorship": "Rydb.",
    "status": "synonym",
    "acceptedName": "Abronia elliptica A. Nelson",
    "classification": "SPECIES:Abronia elliptica A. Nelson|GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 153,
    "inputRank": "",
    "inputName": "Abronia turbinata Torr. ex S. Watson",
    "matchType": "exact",
    "ID": "dIKAHs7-6DPPE_KkIN5-L",
    "rank": "species",
    "label": "Abronia turbinata Torr. ex S. Watson",
    "scientificName": "Abronia turbinata",
    "authorship": "Torr. ex S. Watson",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 154,
    "inputRank": "",
    "inputName": "Abronia umbellata ssp. breviflora",
    "matchType": "variant",
    "ID": "SCk01wqXLbup4WVdyTlqO",
    "rank": "variety",
    "label": "Abronia umbellata var. breviflora (Standl.) L. A. Galloway",
    "scientificName": "Abronia umbellata var. breviflora",
    "authorship": "(Standl.) L. A. Galloway",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abronia umbellata Lam.|GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 155,
    "inputRank": "",
    "inputName": "Abronia villosa S.Watson",
    "matchType": "exact",
    "ID": "P0QGPsChR_eu5hOWJ-6D1",
    "rank": "species",
    "label": "Abronia villosa S. Watson",
    "scientificName": "Abronia villosa",
    "authorship": "S. Watson",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 156,
    "inputRank": "",
    "inputName": "Abronia villosa subsp. aurita Orthodox?",
    "matchType": "variant",
    "ID": "JQwBqywAWi9w3WRaR2WCx0",
    "rank": "variety",
    "label": "Abronia villosa var. aurita (Abrams) Jeps.",
    "scientificName": "Abronia villosa var. aurita",
    "authorship": "(Abrams) Jeps.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "SPECIES:Abronia villosa S. Watson|GENUS:Abronia Juss.|FAMILY:Nyctaginaceae Juss.|ORDER:Caryophyllales Juss. ex Bercht. & J. Presl|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": "QUESTION_MARKS_REMOVED;DOUBTFUL_NAME"
  },
  {
    "inputID": 157,
    "inputRank": "",
    "inputName": "Abrophyllum ornans (F.Muell.) Hook.f.",
    "matchType": "variant",
    "ID": "vrnEX1vIZwt86dygNMuHG",
    "rank": "species",
    "label": "Abrophyllum ornans (F. Muell.) Benth.",
    "scientificName": "Abrophyllum ornans",
    "authorship": "(F. Muell.) Benth.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrophyllum Hook.f.|SUBFAMILY:Carpodetoideae J. Lundb.|FAMILY:Rousseaceae DC.|ORDER:Asterales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 158,
    "inputRank": "",
    "inputName": "Abrotanella emarginata (Gaudich.) Cass.",
    "matchType": "variant",
    "ID": "Goz_DoK_kAQpD8ZuwUcK12",
    "rank": "species",
    "label": "Abrotanella emarginata (Cass. ex Gaudich.) Cass.",
    "scientificName": "Abrotanella emarginata",
    "authorship": "(Cass. ex Gaudich.) Cass.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrotanella Cass.|SUBFAMILY:Asteroideae (Cass.) Lindl.|FAMILY:Asteraceae Dumort.|ORDER:Asterales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 159,
    "inputRank": "",
    "inputName": "Abrotanella linearis",
    "matchType": "variant",
    "ID": "SemiWOk5nocC1xDUOU_lb2",
    "rank": "species",
    "label": "Abrotanella linearis Berggr.",
    "scientificName": "Abrotanella linearis",
    "authorship": "Berggr.",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrotanella Cass.|SUBFAMILY:Asteroideae (Cass.) Lindl.|FAMILY:Asteraceae Dumort.|ORDER:Asterales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  },
  {
    "inputID": 160,
    "inputRank": "",
    "inputName": "Abrotanella submarginata",
    "matchType": "variant",
    "ID": "HS_w6YtYms8h5_byMzMpe0",
    "rank": "species",
    "label": "Abrotanella submarginata A. Gray",
    "scientificName": "Abrotanella submarginata",
    "authorship": "A. Gray",
    "status": "accepted",
    "acceptedName": "",
    "classification": "GENUS:Abrotanella Cass.|SUBFAMILY:Asteroideae (Cass.) Lindl.|FAMILY:Asteraceae Dumort.|ORDER:Asterales|CLASS:Magnoliopsida|PHYLUM:Tracheophyta|SUBKINGDOM:Pteridobiotina Britton & Brown|KINGDOM:Plantae|DOMAIN:Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978",
    "issues": ""
  }
]

export let resultStore = writable<ResultRow[]>(emptyTestRows)
