name: 📄 User Story
description: You discovered something that does not work as desired/expected? Please report that bug!
labels: 'Type: User Story'
projects: [BEXIS2/8]
assignees: 
  - sventhiel
  - geofranzi
  - DavidBlaa
body:
- type: markdown
  attributes:
    value: |
      Thanks ❤️ for taking the time to fill out this user story request form!
- type: checkboxes
  attributes:
    label: "Is there an existing feature request for this?"
    description: "Please check the existing issues first, to see if a similar feature request already exists ([Core/issues](https://github.com/BEXIS2/Core/issues?q=is%3Aissue))."
    options:
    - label: "I searched for a similar feature request and didn't find a suitable one."
      required: true
- type: markdown
  attributes:
    value: |
      Thanks ❤️ for taking the time to fill out this user story request form!
- type: markdown
  attributes:
    label: "Independent"
    description: "Requirements should be as independent of each other as possible, so that they can be implemented in the correct order"
- type: markdown
  attributes:
    label: "Negotiable"
    description: "Requirements should be open to discussion regarding implementation."
- type: textarea
  attributes:
    label: User story description?
    description: Please describe the user story in detail here.
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
