name: 📄 User Story
description: You discovered something that does not work as desired/expected? Please report that bug!
labels: 'Type: User Story'
projects: [BEXIS2/8]
assignees: 
  - sventhiel
  - geofranzi
  - DavidBlaa
body:
- type: markdown
  attributes:
    value: |
      Thanks ❤️ for taking the time to fill out this user story request form!
- type: checkboxes
  attributes:
    label: "Is there an existing feature request for this?"
    description: "Please check the existing issues first, to see if a similar feature request already exists ([Core/issues](https://github.com/BEXIS2/Core/issues?q=is%3Aissue))."
    options:
    - label: "I searched for a similar feature request and didn't find a suitable one."
      required: true
- type: markdown
  attributes:
    value: |
      A user story should comply with the following criteria
- type: markdown
  attributes:
    value: | 
      **Independent** - Requirements should be as independent of each other as possible, so that they can be implemented in the correct order.
      **Negotiable** - Requirements should be open to discussion regarding implementation.
      **Valuable** - Requirements should always generate (self-contained) added value for the community
      **Estimable** - Every requirement must be appreciated. If the team is unable to provide an estimate, it should be discussed again or refined
      **Small** - The size of the requirement should be defined in such a way that it can be implemented in a sprint. 
      **Testable** - A good requirement contains acceptance criteria from the user's point of view and can be tested by the product owner/stakeholder.
- type: textarea
  attributes:
    label: User story
    description: Please describe the user story in detail here.
    placeholder: Tell us what you see!
    value: "Please enter the user story here!"
  validations:
    required: true
- type: textarea
  attributes:
    label: Acceptance criterias
    description: Please enter your acceptance criterias here.
    placeholder: |
      - [ ] a
      - [ ] b
      - [ ] c
    value: ""
  validations:
    required: true
